apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/platform-svc/base
patches:
  - patch: |
      $patch: delete
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: platform-svc-external-secret
  - patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: platform-svc-config
      data:
        DATABASE_HOST: postgres
        DATABASE_PORT: "5432"
        DATABASE_NAME: synapse
        DB_URL: jdbc:postgresql://postgres:5432/synapse
        DB_USERNAME: synapse
        REDIS_HOST: redis
        REDIS_PORT: "6379"
        KAFKA_BROKERS: kafka:9092
images:
  - name: ghcr.io/team-project-final/synapse-platform-svc
    newName: synapse-platform-svc
    newTag: local
