apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: learning-ai-external-secret
  labels:
    app.kubernetes.io/name: learning-ai
    app.kubernetes.io/part-of: synapse
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: TO_BE_PATCHED
    kind: ClusterSecretStore
  target:
    name: learning-ai-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: synapse/dev/learning-ai/openai-api-key
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: synapse/dev/learning-ai/db-password
