apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-svc-pdb
  labels:
    app.kubernetes.io/name: platform-svc
    app.kubernetes.io/part-of: synapse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-svc
