apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: engagement-svc-external-secret
  labels:
    app.kubernetes.io/name: engagement-svc
    app.kubernetes.io/part-of: synapse
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: TO_BE_PATCHED
    kind: ClusterSecretStore
  target:
    name: engagement-svc-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: synapse/dev/engagement-svc/db-password
