apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: synapse-dev-images
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "synapse-*-dev"
      useAnnotations: true
