apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: synapse
  namespace: argocd
spec:
  description: Synapse application project
  sourceRepos:
    - https://github.com/team-project-final/synapse-gitops.git
  destinations:
    - namespace: "synapse-*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
