apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synapse-schema-registry-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/component: schema-registry
    environment: dev
spec:
  project: synapse
  source:
    repoURL: https://github.com/team-project-final/synapse-gitops.git
    targetRevision: main
    path: apps/schema-registry/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: synapse-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
