apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-external-secret
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: synapse
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: TO_BE_PATCHED
    kind: ClusterSecretStore
  target:
    name: gateway-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATA_REDIS_PASSWORD
      remoteRef:
        key: synapse/dev/gateway/redis-password
