apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synapse-local
resources:
  - namespace.yaml
  - infra
  - secrets.yaml
  - gateway.yaml
  - apps/platform-svc
  - apps/engagement-svc
  - apps/knowledge-svc
  - apps/learning-card
  - apps/learning-ai
