apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: learning-card-external-secret
  labels:
    app.kubernetes.io/name: learning-card
    app.kubernetes.io/part-of: synapse
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: TO_BE_PATCHED
    kind: ClusterSecretStore
  target:
    name: learning-card-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: synapse/dev/learning-card/api-key
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: synapse/dev/knowledge-svc/db-password
