apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: synapse-dev

patches:
  - target:
      kind: Deployment
      name: learning-ai
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: learning-ai-config
    patch: |
      - op: replace
        path: /data/LOG_LEVEL
        value: "DEBUG"
      - op: add
        path: /data/DATABASE_HOST
        value: "synapse-dev-postgres.c7emuq20mhyy.ap-northeast-2.rds.amazonaws.com"
      - op: add
        path: /data/DATABASE_PORT
        value: "5432"
      - op: add
        path: /data/DATABASE_NAME
        value: "synapse"
      - op: add
        path: /data/OPENSEARCH_URL
        value: "https://vpc-synapse-dev-qm5l2xdch6nfmkqanpmipou74a.ap-northeast-2.es.amazonaws.com"
      - op: add
        path: /data/LEARNING_AI_DATABASE_URL
        value: "postgresql+asyncpg://synapse_admin@synapse-dev-postgres.c7emuq20mhyy.ap-northeast-2.rds.amazonaws.com:5432/synapse"

  - target:
      kind: ExternalSecret
      name: learning-ai-external-secret
    patch: |
      - op: replace
        path: /spec/secretStoreRef/name
        value: aws-secrets-manager

images:
  - name: ghcr.io/team-project-final/synapse-learning-ai
    newName: 963773969059.dkr.ecr.ap-northeast-2.amazonaws.com/synapse/learning-ai
    newTag: dev-latest
