apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: synapse-dev
patches:
  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: ghcr.io/team-project-final/synapse-frontend
    newName: 963773969059.dkr.ecr.ap-northeast-2.amazonaws.com/synapse/frontend
    newTag: a994c2d29be7a42404d309958c7f5275588ab540
