apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: knowledge-svc-external-secret
  labels:
    app.kubernetes.io/name: knowledge-svc
    app.kubernetes.io/part-of: synapse
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: TO_BE_PATCHED
    kind: ClusterSecretStore
  target:
    name: knowledge-svc-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: synapse/dev/knowledge-svc/db-password
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: synapse/dev/knowledge-svc/s3-access-key
