apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: synapse-dev

patches:
  - target:
      kind: Deployment
      name: platform-svc
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: platform-svc-config
    patch: |
      - op: replace
        path: /data/LOG_LEVEL
        value: "DEBUG"
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: "dev"
      - op: add
        path: /data/DATABASE_HOST
        value: "synapse-dev-postgres.c7emuq20mhyy.ap-northeast-2.rds.amazonaws.com"
      - op: add
        path: /data/DATABASE_PORT
        value: "5432"
      - op: add
        path: /data/DATABASE_NAME
        value: "synapse"
      - op: add
        path: /data/REDIS_HOST
        value: "master.synapse-dev-redis.v6lpdh.apn2.cache.amazonaws.com"
      - op: add
        path: /data/REDIS_PORT
        value: "6379"
      - op: add
        path: /data/KAFKA_BROKERS
        value: "b-1.synapsedevkafka.fark5c.c2.kafka.ap-northeast-2.amazonaws.com:9094,b-2.synapsedevkafka.fark5c.c2.kafka.ap-northeast-2.amazonaws.com:9094"

  - target:
      kind: ExternalSecret
      name: platform-svc-external-secret
    patch: |
      - op: replace
        path: /spec/secretStoreRef/name
        value: aws-secrets-manager

images:
  - name: ghcr.io/team-project-final/synapse-platform-svc
    newName: 963773969059.dkr.ecr.ap-northeast-2.amazonaws.com/synapse/platform-svc
    newTag: dev-latest
